// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: proto/skyeye.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContinuousPingTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId      uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	IntervalMs  uint32 `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	TimeoutMs   uint32 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Destination string `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Count       uint32 `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	// Types that are assignable to Source:
	//
	//	*ContinuousPingTask_Port
	//	*ContinuousPingTask_Ip
	Source isContinuousPingTask_Source `protobuf_oneof:"source"`
}

func (x *ContinuousPingTask) Reset() {
	*x = ContinuousPingTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_skyeye_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContinuousPingTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinuousPingTask) ProtoMessage() {}

func (x *ContinuousPingTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinuousPingTask.ProtoReflect.Descriptor instead.
func (*ContinuousPingTask) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{0}
}

func (x *ContinuousPingTask) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ContinuousPingTask) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *ContinuousPingTask) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ContinuousPingTask) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ContinuousPingTask) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (m *ContinuousPingTask) GetSource() isContinuousPingTask_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (x *ContinuousPingTask) GetPort() string {
	if x, ok := x.GetSource().(*ContinuousPingTask_Port); ok {
		return x.Port
	}
	return ""
}

func (x *ContinuousPingTask) GetIp() string {
	if x, ok := x.GetSource().(*ContinuousPingTask_Ip); ok {
		return x.Ip
	}
	return ""
}

type isContinuousPingTask_Source interface {
	isContinuousPingTask_Source()
}

type ContinuousPingTask_Port struct {
	Port string `protobuf:"bytes,6,opt,name=port,proto3,oneof"`
}

type ContinuousPingTask_Ip struct {
	Ip string `protobuf:"bytes,7,opt,name=ip,proto3,oneof"`
}

func (*ContinuousPingTask_Port) isContinuousPingTask_Source() {}

func (*ContinuousPingTask_Ip) isContinuousPingTask_Source() {}

type ContinuousPingResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId  uint64  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Count   uint32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Loss    uint32  `protobuf:"varint,3,opt,name=loss,proto3" json:"loss,omitempty"`
	RttNano []int64 `protobuf:"varint,4,rep,packed,name=rtt_nano,json=rttNano,proto3" json:"rtt_nano,omitempty"`
}

func (x *ContinuousPingResult) Reset() {
	*x = ContinuousPingResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_skyeye_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContinuousPingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinuousPingResult) ProtoMessage() {}

func (x *ContinuousPingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinuousPingResult.ProtoReflect.Descriptor instead.
func (*ContinuousPingResult) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{1}
}

func (x *ContinuousPingResult) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ContinuousPingResult) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ContinuousPingResult) GetLoss() uint32 {
	if x != nil {
		return x.Loss
	}
	return 0
}

func (x *ContinuousPingResult) GetRttNano() []int64 {
	if x != nil {
		return x.RttNano
	}
	return nil
}

type CancelContinuousTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *CancelContinuousTask) Reset() {
	*x = CancelContinuousTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_skyeye_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelContinuousTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelContinuousTask) ProtoMessage() {}

func (x *CancelContinuousTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelContinuousTask.ProtoReflect.Descriptor instead.
func (*CancelContinuousTask) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{2}
}

func (x *CancelContinuousTask) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ControllerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ControllerMessage_ContinuousPingTask
	//	*ControllerMessage_CancelContinuousTask
	Payload isControllerMessage_Payload `protobuf_oneof:"payload"`
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_skyeye_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{3}
}

func (m *ControllerMessage) GetPayload() isControllerMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ControllerMessage) GetContinuousPingTask() *ContinuousPingTask {
	if x, ok := x.GetPayload().(*ControllerMessage_ContinuousPingTask); ok {
		return x.ContinuousPingTask
	}
	return nil
}

func (x *ControllerMessage) GetCancelContinuousTask() *CancelContinuousTask {
	if x, ok := x.GetPayload().(*ControllerMessage_CancelContinuousTask); ok {
		return x.CancelContinuousTask
	}
	return nil
}

type isControllerMessage_Payload interface {
	isControllerMessage_Payload()
}

type ControllerMessage_ContinuousPingTask struct {
	ContinuousPingTask *ContinuousPingTask `protobuf:"bytes,1,opt,name=continuous_ping_task,json=continuousPingTask,proto3,oneof"`
}

type ControllerMessage_CancelContinuousTask struct {
	CancelContinuousTask *CancelContinuousTask `protobuf:"bytes,2,opt,name=cancel_continuous_task,json=cancelContinuousTask,proto3,oneof"`
}

func (*ControllerMessage_ContinuousPingTask) isControllerMessage_Payload() {}

func (*ControllerMessage_CancelContinuousTask) isControllerMessage_Payload() {}

type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId         string            `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Version         string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities    uint64            `protobuf:"varint,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Hostname        string            `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	InterfaceIpaddr map[string]string `protobuf:"bytes,5,rep,name=interface_ipaddr,json=interfaceIpaddr,proto3" json:"interface_ipaddr,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_skyeye_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{4}
}

func (x *Register) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Register) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Register) GetCapabilities() uint64 {
	if x != nil {
		return x.Capabilities
	}
	return 0
}

func (x *Register) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Register) GetInterfaceIpaddr() map[string]string {
	if x != nil {
		return x.InterfaceIpaddr
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_skyeye_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AgentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_ContinuousPingResult
	Payload isAgentMessage_Payload `protobuf_oneof:"payload"`
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_skyeye_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{6}
}

func (m *AgentMessage) GetPayload() isAgentMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *Register {
	if x, ok := x.GetPayload().(*AgentMessage_Register); ok {
		return x.Register
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetPayload().(*AgentMessage_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *AgentMessage) GetContinuousPingResult() *ContinuousPingResult {
	if x, ok := x.GetPayload().(*AgentMessage_ContinuousPingResult); ok {
		return x.ContinuousPingResult
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_ContinuousPingResult struct {
	ContinuousPingResult *ContinuousPingResult `protobuf:"bytes,3,opt,name=continuous_ping_result,json=continuousPingResult,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_ContinuousPingResult) isAgentMessage_Payload() {}

var File_proto_skyeye_proto protoreflect.FileDescriptor

var file_proto_skyeye_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6b, 0x79, 0x65, 0x79, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x6b, 0x79, 0x65, 0x79, 0x65, 0x22, 0xd7, 0x01, 0x0a,
	0x12, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73, 0x50, 0x69, 0x6e, 0x67, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x4d, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x70, 0x42, 0x08, 0x0a, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x74, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e,
	0x75, 0x6f, 0x75, 0x73, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x6f, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6c, 0x6f, 0x73,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x74, 0x74, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x07, 0x72, 0x74, 0x74, 0x4e, 0x61, 0x6e, 0x6f, 0x22, 0x2f, 0x0a, 0x14,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0xc4, 0x01,
	0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x4e, 0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75,
	0x73, 0x5f, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x6b, 0x79, 0x65, 0x79, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x69,
	0x6e, 0x75, 0x6f, 0x75, 0x73, 0x50, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x00, 0x52,
	0x12, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73, 0x50, 0x69, 0x6e, 0x67, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x54, 0x0a, 0x16, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x6b, 0x79, 0x65, 0x79, 0x65, 0x2e, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73, 0x54, 0x61, 0x73,
	0x6b, 0x48, 0x00, 0x52, 0x14, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x69,
	0x6e, 0x75, 0x6f, 0x75, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x95, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x63, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x50, 0x0a, 0x10, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x5f, 0x69, 0x70, 0x61, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x73, 0x6b, 0x79, 0x65, 0x79, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x70, 0x61, 0x64,
	0x64, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x49, 0x70, 0x61, 0x64, 0x64, 0x72, 0x1a, 0x42, 0x0a, 0x14, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x70, 0x61, 0x64, 0x64, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x29, 0x0a, 0x09,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xd2, 0x01, 0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x6b, 0x79,
	0x65, 0x79, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x6b,
	0x79, 0x65, 0x79, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x48, 0x00,
	0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x54, 0x0a, 0x16, 0x63,
	0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73, 0x5f, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x6b,
	0x79, 0x65, 0x79, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x14, 0x63, 0x6f, 0x6e,
	0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0x52, 0x0a, 0x11,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3d, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x14, 0x2e, 0x73, 0x6b,
	0x79, 0x65, 0x79, 0x65, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x19, 0x2e, 0x73, 0x6b, 0x79, 0x65, 0x79, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_skyeye_proto_rawDescOnce sync.Once
	file_proto_skyeye_proto_rawDescData = file_proto_skyeye_proto_rawDesc
)

func file_proto_skyeye_proto_rawDescGZIP() []byte {
	file_proto_skyeye_proto_rawDescOnce.Do(func() {
		file_proto_skyeye_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_skyeye_proto_rawDescData)
	})
	return file_proto_skyeye_proto_rawDescData
}

var file_proto_skyeye_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_skyeye_proto_goTypes = []any{
	(*ContinuousPingTask)(nil),   // 0: skyeye.ContinuousPingTask
	(*ContinuousPingResult)(nil), // 1: skyeye.ContinuousPingResult
	(*CancelContinuousTask)(nil), // 2: skyeye.CancelContinuousTask
	(*ControllerMessage)(nil),    // 3: skyeye.ControllerMessage
	(*Register)(nil),             // 4: skyeye.Register
	(*Heartbeat)(nil),            // 5: skyeye.Heartbeat
	(*AgentMessage)(nil),         // 6: skyeye.AgentMessage
	nil,                          // 7: skyeye.Register.InterfaceIpaddrEntry
}
var file_proto_skyeye_proto_depIdxs = []int32{
	0, // 0: skyeye.ControllerMessage.continuous_ping_task:type_name -> skyeye.ContinuousPingTask
	2, // 1: skyeye.ControllerMessage.cancel_continuous_task:type_name -> skyeye.CancelContinuousTask
	7, // 2: skyeye.Register.interface_ipaddr:type_name -> skyeye.Register.InterfaceIpaddrEntry
	4, // 3: skyeye.AgentMessage.register:type_name -> skyeye.Register
	5, // 4: skyeye.AgentMessage.heartbeat:type_name -> skyeye.Heartbeat
	1, // 5: skyeye.AgentMessage.continuous_ping_result:type_name -> skyeye.ContinuousPingResult
	6, // 6: skyeye.ManagementService.Stream:input_type -> skyeye.AgentMessage
	3, // 7: skyeye.ManagementService.Stream:output_type -> skyeye.ControllerMessage
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_skyeye_proto_init() }
func file_proto_skyeye_proto_init() {
	if File_proto_skyeye_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_skyeye_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ContinuousPingTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_skyeye_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ContinuousPingResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_skyeye_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CancelContinuousTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_skyeye_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ControllerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_skyeye_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_skyeye_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_skyeye_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*AgentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_skyeye_proto_msgTypes[0].OneofWrappers = []any{
		(*ContinuousPingTask_Port)(nil),
		(*ContinuousPingTask_Ip)(nil),
	}
	file_proto_skyeye_proto_msgTypes[3].OneofWrappers = []any{
		(*ControllerMessage_ContinuousPingTask)(nil),
		(*ControllerMessage_CancelContinuousTask)(nil),
	}
	file_proto_skyeye_proto_msgTypes[6].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_ContinuousPingResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_skyeye_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_skyeye_proto_goTypes,
		DependencyIndexes: file_proto_skyeye_proto_depIdxs,
		MessageInfos:      file_proto_skyeye_proto_msgTypes,
	}.Build()
	File_proto_skyeye_proto = out.File
	file_proto_skyeye_proto_rawDesc = nil
	file_proto_skyeye_proto_goTypes = nil
	file_proto_skyeye_proto_depIdxs = nil
}
