// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/skyeye.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slice         []byte                 `protobuf:"bytes,1,opt,name=slice,proto3" json:"slice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IP) Reset() {
	*x = IP{}
	mi := &file_proto_skyeye_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IP) ProtoMessage() {}

func (x *IP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IP.ProtoReflect.Descriptor instead.
func (*IP) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{0}
}

func (x *IP) GetSlice() []byte {
	if x != nil {
		return x.Slice
	}
	return nil
}

type ContinuousPingJob struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	JobId        uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	IntervalMs   uint32                 `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	TimeoutMs    uint32                 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Destinations []*IP                  `protobuf:"bytes,4,rep,name=destinations,proto3" json:"destinations,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*ContinuousPingJob_Port
	//	*ContinuousPingJob_Ip
	Source        isContinuousPingJob_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinuousPingJob) Reset() {
	*x = ContinuousPingJob{}
	mi := &file_proto_skyeye_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinuousPingJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinuousPingJob) ProtoMessage() {}

func (x *ContinuousPingJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinuousPingJob.ProtoReflect.Descriptor instead.
func (*ContinuousPingJob) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{1}
}

func (x *ContinuousPingJob) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *ContinuousPingJob) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *ContinuousPingJob) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ContinuousPingJob) GetDestinations() []*IP {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *ContinuousPingJob) GetSource() isContinuousPingJob_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ContinuousPingJob) GetPort() string {
	if x != nil {
		if x, ok := x.Source.(*ContinuousPingJob_Port); ok {
			return x.Port
		}
	}
	return ""
}

func (x *ContinuousPingJob) GetIp() *IP {
	if x != nil {
		if x, ok := x.Source.(*ContinuousPingJob_Ip); ok {
			return x.Ip
		}
	}
	return nil
}

type isContinuousPingJob_Source interface {
	isContinuousPingJob_Source()
}

type ContinuousPingJob_Port struct {
	Port string `protobuf:"bytes,5,opt,name=port,proto3,oneof"`
}

type ContinuousPingJob_Ip struct {
	Ip *IP `protobuf:"bytes,6,opt,name=ip,proto3,oneof"`
}

func (*ContinuousPingJob_Port) isContinuousPingJob_Source() {}

func (*ContinuousPingJob_Ip) isContinuousPingJob_Source() {}

type ContinuousPingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Destination   *IP                    `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Loss          uint32                 `protobuf:"varint,4,opt,name=loss,proto3" json:"loss,omitempty"`
	RttNano       []int64                `protobuf:"varint,5,rep,packed,name=rtt_nano,json=rttNano,proto3" json:"rtt_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinuousPingResult) Reset() {
	*x = ContinuousPingResult{}
	mi := &file_proto_skyeye_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinuousPingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinuousPingResult) ProtoMessage() {}

func (x *ContinuousPingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinuousPingResult.ProtoReflect.Descriptor instead.
func (*ContinuousPingResult) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{2}
}

func (x *ContinuousPingResult) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *ContinuousPingResult) GetDestination() *IP {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *ContinuousPingResult) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ContinuousPingResult) GetLoss() uint32 {
	if x != nil {
		return x.Loss
	}
	return 0
}

func (x *ContinuousPingResult) GetRttNano() []int64 {
	if x != nil {
		return x.RttNano
	}
	return nil
}

type CancelContinuousJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelContinuousJob) Reset() {
	*x = CancelContinuousJob{}
	mi := &file_proto_skyeye_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelContinuousJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelContinuousJob) ProtoMessage() {}

func (x *CancelContinuousJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelContinuousJob.ProtoReflect.Descriptor instead.
func (*CancelContinuousJob) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{3}
}

func (x *CancelContinuousJob) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type ControllerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControllerMessage_CancelJob
	//	*ControllerMessage_ContinuousPingJob
	Payload       isControllerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	mi := &file_proto_skyeye_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{4}
}

func (x *ControllerMessage) GetPayload() isControllerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControllerMessage) GetCancelJob() *CancelContinuousJob {
	if x != nil {
		if x, ok := x.Payload.(*ControllerMessage_CancelJob); ok {
			return x.CancelJob
		}
	}
	return nil
}

func (x *ControllerMessage) GetContinuousPingJob() *ContinuousPingJob {
	if x != nil {
		if x, ok := x.Payload.(*ControllerMessage_ContinuousPingJob); ok {
			return x.ContinuousPingJob
		}
	}
	return nil
}

type isControllerMessage_Payload interface {
	isControllerMessage_Payload()
}

type ControllerMessage_CancelJob struct {
	CancelJob *CancelContinuousJob `protobuf:"bytes,1,opt,name=cancel_job,json=cancelJob,proto3,oneof"`
}

type ControllerMessage_ContinuousPingJob struct {
	ContinuousPingJob *ContinuousPingJob `protobuf:"bytes,2,opt,name=continuous_ping_job,json=continuousPingJob,proto3,oneof"`
}

func (*ControllerMessage_CancelJob) isControllerMessage_Payload() {}

func (*ControllerMessage_ContinuousPingJob) isControllerMessage_Payload() {}

type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addrs         []string               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_proto_skyeye_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type Register struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities      uint64                 `protobuf:"varint,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Hostname          string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	NetworkInterfaces []*NetworkInterface    `protobuf:"bytes,5,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_proto_skyeye_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{6}
}

func (x *Register) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Register) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Register) GetCapabilities() uint64 {
	if x != nil {
		return x.Capabilities
	}
	return 0
}

func (x *Register) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Register) GetNetworkInterfaces() []*NetworkInterface {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_skyeye_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_ContinuousPingResult
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_skyeye_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skyeye_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_skyeye_proto_rawDescGZIP(), []int{8}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetContinuousPingResult() *ContinuousPingResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ContinuousPingResult); ok {
			return x.ContinuousPingResult
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_ContinuousPingResult struct {
	ContinuousPingResult *ContinuousPingResult `protobuf:"bytes,3,opt,name=continuous_ping_result,json=continuousPingResult,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_ContinuousPingResult) isAgentMessage_Payload() {}

var File_proto_skyeye_proto protoreflect.FileDescriptor

const file_proto_skyeye_proto_rawDesc = "" +
	"\n" +
	"\x12proto/skyeye.proto\x12\x06skyeye\"\x1a\n" +
	"\x02IP\x12\x14\n" +
	"\x05slice\x18\x01 \x01(\fR\x05slice\"\xd8\x01\n" +
	"\x11ContinuousPingJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\rR\n" +
	"intervalMs\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rR\ttimeoutMs\x12.\n" +
	"\fdestinations\x18\x04 \x03(\v2\n" +
	".skyeye.IPR\fdestinations\x12\x14\n" +
	"\x04port\x18\x05 \x01(\tH\x00R\x04port\x12\x1c\n" +
	"\x02ip\x18\x06 \x01(\v2\n" +
	".skyeye.IPH\x00R\x02ipB\b\n" +
	"\x06source\"\xa0\x01\n" +
	"\x14ContinuousPingResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\x12,\n" +
	"\vdestination\x18\x02 \x01(\v2\n" +
	".skyeye.IPR\vdestination\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x12\n" +
	"\x04loss\x18\x04 \x01(\rR\x04loss\x12\x19\n" +
	"\brtt_nano\x18\x05 \x03(\x03R\arttNano\",\n" +
	"\x13CancelContinuousJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\"\xa9\x01\n" +
	"\x11ControllerMessage\x12<\n" +
	"\n" +
	"cancel_job\x18\x01 \x01(\v2\x1b.skyeye.CancelContinuousJobH\x00R\tcancelJob\x12K\n" +
	"\x13continuous_ping_job\x18\x02 \x01(\v2\x19.skyeye.ContinuousPingJobH\x00R\x11continuousPingJobB\t\n" +
	"\apayload\"<\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\"\xc8\x01\n" +
	"\bRegister\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x03 \x01(\x04R\fcapabilities\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12G\n" +
	"\x12network_interfaces\x18\x05 \x03(\v2\x18.skyeye.NetworkInterfaceR\x11networkInterfaces\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"\xd2\x01\n" +
	"\fAgentMessage\x12.\n" +
	"\bregister\x18\x01 \x01(\v2\x10.skyeye.RegisterH\x00R\bregister\x121\n" +
	"\theartbeat\x18\x02 \x01(\v2\x11.skyeye.HeartbeatH\x00R\theartbeat\x12T\n" +
	"\x16continuous_ping_result\x18\x03 \x01(\v2\x1c.skyeye.ContinuousPingResultH\x00R\x14continuousPingResultB\t\n" +
	"\apayload2R\n" +
	"\x11ManagementService\x12=\n" +
	"\x06Stream\x12\x14.skyeye.AgentMessage\x1a\x19.skyeye.ControllerMessage(\x010\x01B\aZ\x05./;pbb\x06proto3"

var (
	file_proto_skyeye_proto_rawDescOnce sync.Once
	file_proto_skyeye_proto_rawDescData []byte
)

func file_proto_skyeye_proto_rawDescGZIP() []byte {
	file_proto_skyeye_proto_rawDescOnce.Do(func() {
		file_proto_skyeye_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_skyeye_proto_rawDesc), len(file_proto_skyeye_proto_rawDesc)))
	})
	return file_proto_skyeye_proto_rawDescData
}

var file_proto_skyeye_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_skyeye_proto_goTypes = []any{
	(*IP)(nil),                   // 0: skyeye.IP
	(*ContinuousPingJob)(nil),    // 1: skyeye.ContinuousPingJob
	(*ContinuousPingResult)(nil), // 2: skyeye.ContinuousPingResult
	(*CancelContinuousJob)(nil),  // 3: skyeye.CancelContinuousJob
	(*ControllerMessage)(nil),    // 4: skyeye.ControllerMessage
	(*NetworkInterface)(nil),     // 5: skyeye.NetworkInterface
	(*Register)(nil),             // 6: skyeye.Register
	(*Heartbeat)(nil),            // 7: skyeye.Heartbeat
	(*AgentMessage)(nil),         // 8: skyeye.AgentMessage
}
var file_proto_skyeye_proto_depIdxs = []int32{
	0,  // 0: skyeye.ContinuousPingJob.destinations:type_name -> skyeye.IP
	0,  // 1: skyeye.ContinuousPingJob.ip:type_name -> skyeye.IP
	0,  // 2: skyeye.ContinuousPingResult.destination:type_name -> skyeye.IP
	3,  // 3: skyeye.ControllerMessage.cancel_job:type_name -> skyeye.CancelContinuousJob
	1,  // 4: skyeye.ControllerMessage.continuous_ping_job:type_name -> skyeye.ContinuousPingJob
	5,  // 5: skyeye.Register.network_interfaces:type_name -> skyeye.NetworkInterface
	6,  // 6: skyeye.AgentMessage.register:type_name -> skyeye.Register
	7,  // 7: skyeye.AgentMessage.heartbeat:type_name -> skyeye.Heartbeat
	2,  // 8: skyeye.AgentMessage.continuous_ping_result:type_name -> skyeye.ContinuousPingResult
	8,  // 9: skyeye.ManagementService.Stream:input_type -> skyeye.AgentMessage
	4,  // 10: skyeye.ManagementService.Stream:output_type -> skyeye.ControllerMessage
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_skyeye_proto_init() }
func file_proto_skyeye_proto_init() {
	if File_proto_skyeye_proto != nil {
		return
	}
	file_proto_skyeye_proto_msgTypes[1].OneofWrappers = []any{
		(*ContinuousPingJob_Port)(nil),
		(*ContinuousPingJob_Ip)(nil),
	}
	file_proto_skyeye_proto_msgTypes[4].OneofWrappers = []any{
		(*ControllerMessage_CancelJob)(nil),
		(*ControllerMessage_ContinuousPingJob)(nil),
	}
	file_proto_skyeye_proto_msgTypes[8].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_ContinuousPingResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_skyeye_proto_rawDesc), len(file_proto_skyeye_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_skyeye_proto_goTypes,
		DependencyIndexes: file_proto_skyeye_proto_depIdxs,
		MessageInfos:      file_proto_skyeye_proto_msgTypes,
	}.Build()
	File_proto_skyeye_proto = out.File
	file_proto_skyeye_proto_goTypes = nil
	file_proto_skyeye_proto_depIdxs = nil
}
